try {
    console.log(a)
    console.log('teste')
    console.log('fechando meu mano')
} catch(e) {
    console.log('erro')
} finally {
    console.log('Terminando isso aqui meu brother')
}